BIN/* usr/share/freeplane

DOC/* usr/share/doc/freeplane
DOC/* usr/share/freeplane/doc

freeplane_framework/script/freeplane.svg usr/share/icons/hicolor/scalable/apps
freeplane_framework/script/freeplane.png usr/share/icons/hicolor/32x32/apps
48x48/freeplane.png usr/share/icons/hicolor/48x48/apps
64x64/freeplane.png usr/share/icons/hicolor/64x64/apps
128x128/freeplane.png usr/share/icons/hicolor/128x128/apps

freeplane_framework/script/freeplane.png usr/share/pixmaps
freeplane.xpm usr/share/pixmaps

debian/freeplane.desktop usr/share/applications
